name: Push-to-EC2

# Trigger deployment only on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: (Optional) Build Docker image if applicable
      - name: Build Docker image
        run: |
          docker build -t 21days-api:latest .

      # Step 3: Log in to Docker Hub (Optional)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Push Docker image to Docker Hub (Optional)
      - name: Push Docker image to Docker Hub
        run: |
          docker push your-image-name:latest

      # Step 5: Execute SSH commands remotely on EC2
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull patthadon/21days-api
            sudo docker stop 21days-api
            sudo docker rm 21days-api
            sudo docker network connect nginx-proxy_default 21days-api
